[build]
target = "target.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
runner = "run.sh"